# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_auto_20180219_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='course',
            field=models.CharField(max_length=255, null='True'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(help_text='This is name', max_length=255, verbose_name='Instructor Name'),
        ),
    ]
